//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaviCurdWebApp.MyDB_Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDETAIL
    {
        public int SID { get; set; }
        public string SNAME { get; set; }
        public Nullable<int> FEE { get; set; }
        public string ROLL { get; set; }
    }
}
